language: node_js
node_js:
  - node
dist: bionic
sudo: required

branches:
  only:
   - master
before_script:
  - npm install -g @angular/cli

script:
  # - npm run test-headless
  - ng build --prod --base-href https://carine18.github.io/mybitcoin
 
 notifications:  
  # email:  
  #   recipients:  
  #   - carinengbeechin@gmail.com 
    on_success: always  
    on_failure: always
 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mybitcoin
  on:
    branch: master


